### ISSUE TITLE
 Error :  Concurrent modification during iteration: _LinkedHashMap len:0.

### ISSUE THREAD

**Issue by hrxiang** [livekit/client-sdk-flutter#120]
**repeat disconnect,  connect,  disconnect,  connect ............**

```
I/flutter ( 9546): Error :  Concurrent modification during iteration: _LinkedHashMap len:0.
I/flutter ( 9546): StackTrace :  #0      _CompactIterator.moveNext (dart:collection-patch/compact_hash.dart:615:7)
I/flutter ( 9546): #1      RoomPrivateMethods._cleanUp (package:livekit_client/src/core/room.dart:495:45)
I/flutter ( 9546): <asynchronous suspension>
I/flutter ( 9546): #2      new Room.<anonymous closure> (package:livekit_client/src/core/room.dart:100:7)
I/flutter ( 9546): <asynchronous suspension>
I/flutter ( 9546): #3      _Disposer._dispose (package:livekit_client/src/support/disposable.dart:29:11)
I/flutter ( 9546): <asynchronous suspension>
I/flutter ( 9546): #4      DisposableChangeNotifier.dispose (package:livekit_client/src/support/disposable.dart:53:12)
I/flutter ( 9546): <asynchronous suspension>
I/flutter ( 9546): #5      LiveKitClient.connect (package:livekit_client/src/livekit.dart:28:7)

```

**Comment by hiroshihorie** [comment]
looking into this one ! can I see the code you use to reproduce this ?

**Comment by hiroshihorie** [comment]
I think this is due to not awaiting connect / disconnect.
If it still happens please re-open the issue 🙂
