### ISSUE TITLE
[bug] MediaStreamTrack has been disposed

### ISSUE THREAD

**Issue by furkanKotic** [livekit/client-sdk-flutter#248]
**Describe the bug**

```
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: PlatformException(error, MediaStreamTrack has been disposed., null, java.lang.IllegalStateException: MediaStreamTrack has been disposed.
	at org.webrtc.MediaStreamTrack.checkMediaStreamTrackExists(Unknown Source:13)
	at org.webrtc.MediaStreamTrack.enabled(Unknown Source:0)
	at com.cloudwebrtc.webrtc.MethodCallHandlerImpl.mediaStreamTrackSetEnabled(Unknown Source:14)
	at com.cloudwebrtc.webrtc.MethodCallHandlerImpl.onMethodCall(Unknown Source:905)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(Unknown Source:17)
	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(Unknown Source:18)
	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0(Unknown Source:40)
	at io.flutter.embedding.engine.dart.DartMessenger.a(Unknown Source:0)
	at io.flutter.embedding.engine.dart.a.run(Unknown Source:12)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:226)
	at android.os.Looper.loop(Looper.java:313)
	at android.app.ActivityThread.main(ActivityThread.java:8741)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:571)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
)
       at StandardMethodCodec.decodeEnvelope(message_codecs.dart:653)
       at MethodChannel._invokeMethod(platform_channel.dart:315)
```
I saw this error on Firebase. I don't know how can it reproduce but most of the users i have are encountering this error.

**Platform information**

* **Flutter version**: Flutter 3.7.5
* **Plugin version**: livekit_client: ^1.2.0
* **Flutter target OS**: Android/iOS

**Comment by cloudwebrtc** [comment]
Don't worry, I reproduced this bug in a recent test, it will be fixed by next week at the latest

**Comment by furkanKotic** [comment]
I am getting the same error in v1.2.2 version. Did you make any changes?

**Comment by gladbhex** [comment]
Still has the issue. v1.3.0. @furkanKotic were you able to solve this?

`Exception has occurred.
PlatformException (PlatformException(error, MediaStreamTrack has been disposed., null, java.lang.IllegalStateException: MediaStreamTrack has been disposed.
	at org.webrtc.MediaStreamTrack.checkMediaStreamTrackExists(MediaStreamTrack.java:120)
	at org.webrtc.MediaStreamTrack.enabled(MediaStreamTrack.java:93)
	at com.cloudwebrtc.webrtc.MethodCallHandlerImpl.mediaStreamTrackSetEnabled(MethodCallHandlerImpl.java:1304)
	at com.cloudwebrtc.webrtc.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:351)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7884)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
))`

**Comment by gladbhex** [comment]
The same issue with v1.3.0, happens when the remote participant disconnects from the room. Using this for a one-to-one chat, and when the remote participant disconnects, the below exception is thrown. Not tested for multiple remote participants. 
Flutter v3.7.9

`PlatformException (PlatformException(error, MediaStreamTrack has been disposed., null, java.lang.IllegalStateException: MediaStreamTrack has been disposed.
	at org.webrtc.MediaStreamTrack.checkMediaStreamTrackExists(MediaStreamTrack.java:120)
	at org.webrtc.MediaStreamTrack.enabled(MediaStreamTrack.java:93)
	at com.cloudwebrtc.webrtc.MethodCallHandlerImpl.mediaStreamTrackSetEnabled(MethodCallHandlerImpl.java:1316)
	at com.cloudwebrtc.webrtc.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:350)
	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:258)
	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:295)
	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:322)
	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7884)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
))`
