### ISSUE TITLE
[bug] "peerConnection is null" loop

### ISSUE THREAD

**Issue by furkanKotic** [livekit/client-sdk-flutter#299]
**Describe the bug**
The following log appears constantly in the logs:

```
D/FlutterWebRTCPlugin(21647): peerConnectionGetStats(): peerConnection is null
I/flutter (21647): ----------------FIREBASE CRASHLYTICS----------------
I/flutter (21647): Unable to RTCRtpReceiverNative::getStats: peerConnectionGetStats(): peerConnection is null
I/flutter (21647): #0      RTCRtpReceiverNative.getStats (package:flutter_webrtc/src/native/rtc_rtp_receiver_impl.dart:45:7)
I/flutter (21647): <asynchronous suspension>
I/flutter (21647): #1      RemoteAudioTrack.getReceiverStats (package:livekit_client/src/track/remote/audio.dart:91:19)
I/flutter (21647): <asynchronous suspension>
I/flutter (21647): #2      RemoteAudioTrack.monitorReceiver (package:livekit_client/src/track/remote/audio.dart:75:19)
I/flutter (21647): <asynchronous suspension>
I/flutter (21647): ----------------------------------------------------
```

**To Reproduce**
it happened when I left the room, the log was repeated continuously until the app was closed.

**Platform information**

* **Plugin version**: livekit_client: ^1.3.4
* **Flutter target OS**: Android

**Comment by cloudwebrtc** [comment]
hey @furkanKotic,  Is there any other log context before this log? It looks like `remoteTrack.stop();` is not being called

**Comment by furkanKotic** [comment]
These logs are new:

```
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Unsupported operation: Infinity or NaN toInt
       at double.toInt(dart:core)
       at LocalVideoTrack.monitorSender.<fn>(video.dart:49)
       at _LinkedHashMapMixin.forEach(dart:collection)
       at LocalVideoTrack.monitorSender(video.dart:47)
```

```
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Unable to RTCRtpSenderNative::getStats: peerConnectionGetStats(): MediaStreamTrack not found for id: 274cfd25-a580-4067-af7c-1f1b80b75aee
       at RTCRtpSenderNative.getStats(rtc_rtp_sender_impl.dart:63)
       at LocalAudioTrack.getSenderStats(audio.dart:57)
       at LocalAudioTrack.monitorSender(audio.dart:41)
```

```
Fatal Exception: io.flutter.plugins.firebase.crashlytics.FlutterError: Unable to RTCRtpReceiverNative::getStats: peerConnectionGetStats(): peerConnection is null
       at RTCRtpReceiverNative.getStats(rtc_rtp_receiver_impl.dart:45)
       at RemoteAudioTrack.getReceiverStats(audio.dart:91)
       at RemoteAudioTrack.monitorReceiver(audio.dart:75)
```

**Comment by furkanKotic** [comment]
These are the IOS logs:

```
Unable to RTCRtpSenderNative::getStats: Error
Fatal Exception: FlutterError
0  ???                            0x0 RTCRtpSenderNative.getStats + 63 (rtc_rtp_sender_impl.dart:63)
1  ???                            0x0 LocalAudioTrack.getSenderStats + 57 (audio.dart:57)
2  ???                            0x0 LocalAudioTrack.monitorSender + 41 (audio.dart:41)
```

```
Unable to RTCRtpReceiverNative::getStats: Error: peerConnection not found!
Fatal Exception: FlutterError
0  ???                            0x0 RTCRtpReceiverNative.getStats + 45 (rtc_rtp_receiver_impl.dart:45)
1  ???                            0x0 RemoteAudioTrack.getReceiverStats + 91 (audio.dart:91)
2  ???                            0x0 RemoteAudioTrack.monitorReceiver + 75 (audio.dart:75)
```

**Comment by cloudwebrtc** [comment]
@furkanKotic , can you try this branch [fix/track-not-stop-stats-monotor-correctly](https://github.com/livekit/client-sdk-flutter/pull/306)?

**Comment by furkanKotic** [comment]
@cloudwebrtc The scenario was that the error was occurring when there was an internet outage just before leaving the room.

When I try the fix above, the log no longer appears. **The problem seems solved.** 
Thanks.

**Comment by cloudwebrtc** [comment]
hey @furkanKotic, Thanks for your testing and confirmation.
