### ISSUE TITLE
[bug]Timed out waiting for PeerConnection to connect, please check your network for ice connectivity

### ISSUE THREAD

**Issue by simanlx** [livekit/client-sdk-flutter#480]
E/flutter (28797): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: LiveKit Exception: [MediaConnectException] Timed out waiting for PeerConnection to connect, please check your network for ice connectivity
E/flutter (28797): #0      Engine.connect.<anonymous closure> (package:livekit_client/src/core/engine.dart:203:26)
E/flutter (28797): #1      _RootZone.run (dart:async/zone.dart:1655:54)
E/flutter (28797): #2      Future.timeout.<anonymous closure> (dart:async/future_impl.dart:938:34)
E/flutter (28797): #3      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
E/flutter (28797): #4      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
E/flutter (28797): #5      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
E/flutter (28797): #6      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189:12)

升级 2.0.2

**Comment by vuminhhieucareer172** [comment]
Same here. Do you have any information about the solution?

**Comment by mkgor** [comment]
getting the same issue

**Comment by kNoAPP** [comment]
Starting to see this too:
```
Uncaught Error: Failed to construct 'RTCPeerConnection': '[turn:ip-129-146-71-91.host.livekit.cloud:3478?transport=udp, turn:129.146.71.91:3478?transport=udp, turns:ophoenix1a.turn.livekit.cloud:443?transport=tcp]' is not a valid URL.

main.dart.js:5215 Uncaught LiveKit Exception: [minified:Mc] Timed out waiting for PeerConnection to connect, please check your network for ice connectivity.
```

**Comment by furkanKotic** [comment]
I have this problem too. I'm also getting this warning on your test site. It may be related to knowledge.

![image](https://github.com/livekit/client-sdk-flutter/assets/92918781/777b1329-f442-478b-97b2-8cf29070e9f0)

**Comment by papa-tezda** [comment]
This probably happens after the first call. You need to call room.disconnect() after a call closes or is cancelled.

**Comment by jielimi** [comment]
Do you have any information about the solution?

**Comment by kNoAPP** [comment]
If I remember correctly, was able to resolve this issue by reverting Flutter and LiveKit to older versions (at the time). I have since been able to go back to the latest versions of both and be fine.

I haven't had this issue reoccur in several months. There was a LiveKit Slack thread a while back where @cloudwebrtc provided good information. You might check there next?

Here's what solved it for me:
> , please temporarily roll back the SDK version to v2.1.0 and use Flutter 3.16.8. Found some new issues for v2.1.1 and above, which may be related to package:web. The old dart-webrtc no longer works stably after migrating to flutter 3.19.x.
> -- Duan

But again, I'm running latest Flutter and LiveKit now and don't have this issue. So this solution, while

**Comment by savan-sangani** [comment]
This probably happens after one call ongoing and during second call appears then try to connect second call.


 [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: LiveKit Exception: [MediaConnectException] Timed out waiting for PeerConnection to connect, please check your network for ice connectivity
#0      Engine.connect.<anonymous closure> (package:livekit_client/src/core/engine.dart:213:26)
engine.dart:213
#1      _RootZone.run (dart:async/zone.dart:1655:54)
zone.dart:1655
#2      Future.timeout.<anonymous closure> (dart:async/future_impl.dart:957:34)
future_impl.dart:957
#3      Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
timer_patch.dart:18
#4      _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
timer_impl.dart:398
#5      _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
timer_impl.dart:429
#6      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
