### ISSUE TITLE
Screen share throws `Unable to getDisplayMedia` on Android

### ISSUE THREAD

**Issue by acgacgacgacg** [livekit/client-sdk-flutter#555]
**Describe the bug**

On Android emulator with Android 14, the screen share throws the following error when turned on -> off -> on.

```
Unable to getDisplayMedia: Don't re-use the resultData to retrieve the same projection instance, and don't use a token that has timed out. Don't take multiple captures by invoking MediaProjection#createVirtualDisplay multiple times on the same instance.
```

This does not happen on iOS or Android device with Android 12.
We do not have an Android device which supports Android 14 to reproduce this issue.

**To Reproduce**

Use the example, turn on screen share then turn off, then turn on.

**Expected behavior**

No error thrown.

**Platform information**

Android Emulator with Android 14

* **Flutter version**: 

```
[✓] Flutter (Channel stable, 3.19.6, on macOS 13.5.2 22G91 darwin-arm64, locale zh-Hans-JP)
    • Flutter version 3.19.6 on channel stable at /Users/gokaten/fvm/versions/3.19.6
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 54e66469a9 (3 months ago), 2024-04-17 13:08:03 -0700
    • Engine revision c4cd48e186
    • Dart version 3.3.4
    • DevTools version 2.31.1

[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.1)
    • Android SDK at /Users/gokaten/Library/Android/sdk
    • Platform android-34, build-tools 33.0.1
    • Java binary at: /Applications/Android Studio.app/Contents/jbr/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15C500b
    • CocoaPods version 1.14.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2023.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.9+0-17.0.9b1087.7-11185874)
```

* **Flutter console log**: 

```
E/MethodChannel#FlutterWebRTC.Method(24614): java.lang.SecurityException: Don't re-use the resultData to retrieve the same projection instance, and don't use a token that has timed out. Don't take multiple captures by invoking MediaProjection#createVirtualDisplay multiple times on the same instance.
E/MethodChannel#FlutterWebRTC.Method(24614):    at android.os.Parcel.createExceptionOrNull(Parcel.java:3057)
E/MethodChannel#FlutterWebRTC.Method(24614):    at android.os.Parcel.createException(Parcel.java:3041)
E/MethodChannel#FlutterWebRTC.Method(24614):    at android.os.Parcel.readException(Parcel.java:3024)
E/MethodChannel#FlutterWebRTC.Method(24614):    at android.os.Parcel.readException(Parcel.java:2966)
E/MethodChannel#FlutterWebRTC.Method(24614):    at android.hardware.display.IDisplayManager$Stub$Proxy.createVirtualDisplay(IDisplayManager.java:1425)
E/MethodChannel#FlutterWebRTC.Method(24614):    at android.hardware.display.DisplayManagerGlobal.createVirtualDisplay(DisplayManagerGlobal.java:643)
E/MethodChannel#FlutterWebRTC.Method(24614):    at android.hardware.display.DisplayManager.createVirtualDisplay(DisplayManager.java:1134)
E/MethodChannel#FlutterWebRTC.Method(24614):    at android.media.projection.MediaProjection.createVirtualDisplay(MediaProjection.java:247)
E/MethodChannel#FlutterWebRTC.Method(24614):    at android.media.projection.MediaProjection.createVirtualDisplay(MediaProjection.java:216)
E/MethodChannel#FlutterWebRTC.Method(24614):    at com.cloudwebrtc.webrtc.OrientationAwareScreenCapturer.createVirtualDisplay(OrientationAwareScreenCapturer.java:183)
E/MethodChannel#FlutterWebRTC.Method(24614):    at com.cloudwebrtc.webrtc.OrientationAwareScreenCapturer.startCapture(OrientationAwareScreenCapturer.java:123)
E/MethodChannel#FlutterWebRTC.Method(24614):    at com.cloudwebrtc.webrtc.GetUserMediaImpl.getDisplayMedia(GetUserMediaImpl.java:560)
E/MethodChannel#FlutterWebRTC.Method(24614):    at com.cloudwebrtc.webrtc.GetUserMediaImpl.getDisplayMedia(GetUserMediaImpl.java:512)
E/MethodChannel#FlutterWebRTC.Method(24614):    at com.cloudwebrtc.webrtc.MethodCallHandlerImpl.getDisplayMedia(MethodCallHandlerImpl.java:1404)
E/MethodChannel#FlutterWebRTC.Method(24614):    at com.cloudwebrtc.webrtc.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:634)
E/MethodChannel#FlutterWebRTC.Method(24614):    at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
E/MethodChannel#FlutterWebRTC.Method(24614):    at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
E/MethodChannel#FlutterWebRTC.Method(24614):    at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
E/MethodChannel#FlutterWebRTC.Method(24614):    at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
E/MethodChannel#FlutterWebRTC.Method(24614):    at android.os.Handler.handleCallback(Handler.java:958)
E/MethodChannel#FlutterWebRTC.Method(24614):    at android.os.Handler.dispatchMessage(Handler.java:99)
E/MethodChannel#FlutterWebRTC.Method(24614):    at android.os.Looper.loopOnce(Looper.java:205)
E/MethodChannel#FlutterWebRTC.Method(24614):    at android.os.Looper.loop(Looper.java:294)
E/MethodChannel#FlutterWebRTC.Method(24614):    at android.app.ActivityThread.main(ActivityThread.java:8177)
E/MethodChannel#FlutterWebRTC.Method(24614):    at java.lang.reflect.Method.invoke(Native Method)
E/MethodChannel#FlutterWebRTC.Method(24614):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
E/MethodChannel#FlutterWebRTC.Method(24614):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
E/MethodChannel#FlutterWebRTC.Method(24614): Caused by: android.os.RemoteException: Remote stack trace:
E/MethodChannel#FlutterWebRTC.Method(24614):    at com.android.server.media.projection.MediaProjectionManagerService$MediaProjection.isValid(MediaProjectionManagerService.java:1094)
E/MethodChannel#FlutterWebRTC.Method(24614):    at com.android.server.display.DisplayManagerService.createVirtualDisplayInternal(DisplayManagerService.java:1447)
E/MethodChannel#FlutterWebRTC.Method(24614):    at com.android.server.display.DisplayManagerService.-$$Nest$mcreateVirtualDisplayInternal(DisplayManagerService.java:0)
E/MethodChannel#FlutterWebRTC.Method(24614):    at com.android.server.display.DisplayManagerService$BinderService.createVirtualDisplay(DisplayManagerService.java:3706)
E/MethodChannel#FlutterWebRTC.Method(24614):    at android.hardware.display.IDisplayManager$Stub.onTransact(IDisplayManager.java:730)
E/MethodChannel#FlutterWebRTC.Method(24614): 
I/flutter (24614): ----------------FIREBASE CRASHLYTICS----------------
I/flutter (24614): Unable to getDisplayMedia: Don't re-use the resultData to retrieve the same projection instance, and don't use a token that has timed out. Don't take multiple captures by invoking MediaProjection#createVirtualDisplay multiple times on the same instance.
I/flutter (24614): #0      MediaDeviceNative.getDisplayMedia (package:flutter_webrtc/src/native/mediadevices_impl.dart:68:7)
I/flutter (24614): <asynchronous suspension>
I/flutter (24614): #1      LocalTrack.createStream (package:livekit_client/src/track/local/local.dart:172:16)
I/flutter (24614): <asynchronous suspension>
I/flutter (24614): #2      LocalVideoTrack.createScreenShareTracksWithAudio (package:livekit_client/src/track/local/video.dart:223:20)
I/flutter (24614): <asynchronous suspension>
I/flutter (24614): #3      LocalParticipant.setSourceEnabled (package:livekit_client/src/participant/local.dart:597:26)
I/flutter (24614): <asynchronous suspension>
I/flutter (24614): #4      RoomVoiceCallsHandler.toggleScreenShare (package:app/providers/screenProvider/room_voice_calls_handler.dart:287:5)
I/flutter (24614): <asynchronous suspension>
I/flutter (24614): ----------------------------------------------------
```

**Comment by cloudwebrtc** [comment]
Please refer to this PR
https://github.com/livekit/client-sdk-flutter/pull/545
