### ISSUE TITLE
exception thrown when muting tracks (chrome windows)

### ISSUE THREAD

**Issue by alex-bluetrain** [livekit/client-sdk-flutter#56]
I'm running the example from client-sdk-flutter and the mute (either video or audio) throws an exception:

here's the exception for video muting:
```
FINE: setSourceEnabled(source: TrackSource.camera, enabled: false)
FINE: LocalTrack.mute() muted: false
FINE: LocalVideoTrack#672310356.disable() disabling MediaStreamTrackWeb#787289586...
Error: Unsupported operation: Platform._operatingSystem
    at Object.throw_ [as throw] (http://localhost:54174/dart_sdk.js:5061:11)
    at Function._operatingSystem (http://localhost:54174/dart_sdk.js:54665:17)
    at Function.get operatingSystem [as operatingSystem] (http://localhost:54174/dart_sdk.js:54711:27)
    at get _operatingSystem (http://localhost:54174/dart_sdk.js:54624:27)
    at Function.desc.get [as _operatingSystem] (http://localhost:54174/dart_sdk.js:5552:17)
    at get isWindows (http://localhost:54174/dart_sdk.js:54642:26)
    at Function.desc.get [as isWindows] (http://localhost:54174/dart_sdk.js:5552:17)
    at video$.LocalVideoTrack.__.mute (http://localhost:54174/packages/livekit_client/src/publication/local_track_publication.dart.lib.js:4978:26)
    at mute.next (<anonymous>)
    at http://localhost:54174/dart_sdk.js:38640:33
    at _RootZone.runUnary (http://localhost:54174/dart_sdk.js:38511:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:54174/dart_sdk.js:33713:29)
    at handleValueCallback (http://localhost:54174/dart_sdk.js:34265:49)
    at Function._propagateToListeners (http://localhost:54174/dart_sdk.js:34303:17)
    at _Future.new.[_completeWithValue] (http://localhost:54174/dart_sdk.js:34151:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:54174/dart_sdk.js:34172:35)
    at Object._microtaskLoop (http://localhost:54174/dart_sdk.js:38778:13)
    at _startMicrotaskLoop (http://localhost:54174/dart_sdk.js:38784:13)
    at http://localhost:54174/dart_sdk.js:34519:9
```

I'm testing it on latest main commit `3d5e8a7dd846672324ecb476fd854d6557a13379`

flutter doctor:
```
$ flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 2.8.0, on Microsoft Windows [Version 10.0.19043.1348], locale es-AR)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Community 2019 16.10.4)
[√] Android Studio (version 4.1)
[√] VS Code (version 1.62.3)
[√] Connected device (3 available)

• No issues found!
```

**Comment by hiroshihorie** [comment]
thanks @alex-bluetrain , this might be a flutter_webrtc issue I will look into today.

**Comment by hiroshihorie** [comment]
Should be fixed in https://github.com/livekit/client-sdk-flutter/commit/b24fad0f3b6ae610ced1b44108d7fa32ca759dd9
Thanks for the report!

**Comment by alex-bluetrain** [comment]
thanks @hiroshihorie there are no more exceptions now.
