### ISSUE TITLE
[bug][Android] java.lang.RuntimeException: android.opengl.GLException: Failed to create EGL context: 0x3000

### ISSUE THREAD

**Issue by lsq286224380** [livekit/client-sdk-flutter#623]
Failed to handle method call
                                                                                                   

>  java.lang.RuntimeException: android.opengl.GLException: Failed to create EGL context: 0x3000

                                                                                                    	at org.webrtc.EglBase14Impl.createEglContext(EglBase14Impl.java:336)
                                                                                                    	at org.webrtc.EglBase14Impl.-$$Nest$smcreateEglContext(Unknown Source:0)
                                                                                                    	at org.webrtc.EglBase14Impl$EglConnection.<init>(EglBase14Impl.java:66)
                                                                                                    	at org.webrtc.EglBase$EglConnection.create(EglBase.java:50)
                                                                                                    	at org.webrtc.EglThread.lambda$create$0(EglThread.java:64)
                                                                                                    	at org.webrtc.EglThread$$ExternalSyntheticLambda2.call(Unknown Source:4)
                                                                                                    	at org.webrtc.ThreadUtils$3.run(ThreadUtils.java:173)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:873)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at org.webrtc.EglThread$HandlerWithExceptionCallbacks.dispatchMessage(EglThread.java:96)
                                                                                                    	at android.os.Looper.loop(Looper.java:226)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:65)
                                                                                                    	at org.webrtc.ThreadUtils.invokeAtFrontUninterruptibly(ThreadUtils.java:184)
                                                                                                    	at org.webrtc.EglThread.create(EglThread.java:57)
                                                                                                    	at org.webrtc.EglThread.create(EglThread.java:79)
                                                                                                    	at org.webrtc.EglRenderer.init(EglRenderer.java:218)
                                                                                                    	at org.webrtc.EglRenderer.init(EglRenderer.java:229)
                                                                                                    	at com.cloudwebrtc.webrtc.SurfaceTextureRenderer.init(SurfaceTextureRenderer.java:61)
                                                                                                    	at com.cloudwebrtc.webrtc.SurfaceTextureRenderer.init(SurfaceTextureRenderer.java:41)
                                                                                                    	at com.cloudwebrtc.webrtc.FlutterRTCVideoRenderer.<init>(FlutterRTCVideoRenderer.java:106)
                                                                                                    	at com.cloudwebrtc.webrtc.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:517)
                                                                                                    	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
                                                                                                    	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
                                                                                                    	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
                                                                                                    	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:873)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loop(Looper.java:226)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:7224)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:500)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:913)
                                                                                                    Caused by: android.opengl.GLException: Failed to create EGL context: 0x3000
                                                                                                    	at org.webrtc.EglBase14Impl.createEglContext(EglBase14Impl.java:336)
                                                                                                    	at org.webrtc.EglBase14Impl.-$$Nest$smcreateEglContext(Unknown Source:0)
                                                                                                    	at org.webrtc.EglBase14Impl$EglConnection.<init>(EglBase14Impl.java:66)
                                                                                                    	at org.webrtc.EglBase$EglConnection.create(EglBase.java:50)
                                                                                                    	at org.webrtc.EglThread.lambda$create$0(EglThread.java:64)
                                                                                                    	at org.webrtc.EglThread$$ExternalSyntheticLambda2.call(Unknown Source:4)
                                                                                                    	at org.webrtc.ThreadUtils$3.run(ThreadUtils.java:173)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:873)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at org.webrtc.EglThread$HandlerWithExceptionCallbacks.dispatchMessage(EglThread.java:96)
                                                                                                    	at android.os.Looper.loop(Looper.java:226)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:65)

**Comment by lsq286224380** [comment]
2.2.6/2.2.7/2.3.0都遇到了此报错 ，报错后视频无法渲染。我们是在视频列表点击item放大视频单独展示时遇到的此问题。
