### ISSUE TITLE
flutter example can not work with livekit-cli

### ISSUE THREAD

**Issue by ZestyXin** [livekit/client-sdk-flutter#84]
## what happend

flutter example will broken when use livekit-cli publish a h264 file. 

![2022-02-17-170406_1920x1080_scrot](https://user-images.githubusercontent.com/47104456/154605214-6373ed6e-9f60-4e14-8ac3-d0a7f770219c.png)

## what did i do

1. run livekit-server

```
LIVEKIT_KEYS="<key>: <secret>" ./bin/livekit-server --dev
```

2. run flutter example in chrome and connect to server

```
cd client-sdk-flutter-0.5.6/example
flutter run
```

3. use livekit-cli to publish h264 file

```
livekit-cli join-room --api-key <key> --api-secret <secret> -room room1 --identity 173af7c0-8a50-11ec-af69-af12c83724a1 --publish output.h264
```

h264 file generated by ffmpeg

```
ffmpeg -y -re -f lavfi -i testsrc=duration=60:size=720x1080:rate=25:decimals=4 -vcodec libx264 -r:v 25 output.h264
```

## Version

livekit-cli
```
$ livekit-cli --version
livekit-cli version 0.6.6
```

livekit-server
```
$ ./bin/livekit-server --version
livekit-server version 0.15.4
```
client-sdk-flutter: 0.5.6

## Other

i run with client-sdk-js, and it work.

But how can i run flutter example normally with livekit-cli

![2022-02-17-172046_1920x1080_scrot](https://user-images.githubusercontent.com/47104456/154605550-61f336ec-7789-452f-a311-3f5369ecf86f.png)

flutter run output
```
Launching lib/main.dart on Chrome in debug mode...
Waiting for connection from debug service on Chrome...             22.7s
This app is linked to the debug service: ws://127.0.0.1:46627/SMHlp3bbfsA=/ws
Debug service listening on ws://127.0.0.1:46627/SMHlp3bbfsA=/ws

💪 Running with sound null safety 💪

🔥  To hot restart changes while running, press "r" or "R".
For a more detailed help message, press "h". To quit, press "q".

An Observatory debugger and profiler on Chrome is available at: http://127.0.0.1:46627/SMHlp3bbfsA=
The Flutter DevTools debugger and profiler on Chrome is available at: http://127.0.0.1:9100?uri=http://127.0.0.1:46627/SMHlp3bbfsA=
Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/keyboard_binding.dart:352:16
result != null
"Invalid modifier location: Control, 0"
    at Object.throw_ [as throw] (http://localhost:44665/dart_sdk.js:5067:11)
    at Object.assertFailed (http://localhost:44665/dart_sdk.js:4992:15)
    at http://localhost:44665/dart_sdk.js:170075:39
    at _engine.KeyboardConverter.new.[_handleEvent] (http://localhost:44665/dart_sdk.js:170081:25)
    at _engine.KeyboardConverter.new.handleEvent (http://localhost:44665/dart_sdk.js:170168:27)
    at http://localhost:44665/dart_sdk.js:169808:76
    at loggedHandler (http://localhost:44665/dart_sdk.js:169785:18)
Error: Assertion failed: org-dartlang-sdk:///flutter_web_sdk/lib/_engine/engine/keyboard_binding.dart:352:16
result != null
"Invalid modifier location: Control, 0"
    at Object.throw_ [as throw] (http://localhost:44665/dart_sdk.js:5067:11)
    at Object.assertFailed (http://localhost:44665/dart_sdk.js:4992:15)
    at http://localhost:44665/dart_sdk.js:170075:39
    at _engine.KeyboardConverter.new.[_handleEvent] (http://localhost:44665/dart_sdk.js:170081:25)
    at _engine.KeyboardConverter.new.handleEvent (http://localhost:44665/dart_sdk.js:170168:27)
    at http://localhost:44665/dart_sdk.js:169809:74
    at loggedHandler (http://localhost:44665/dart_sdk.js:169785:18)
Connecting with url: ws://localhost:7880, token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2NDUwOTIxMjgsImlzcyI6IkFQSVZVTDlHSGdZWGdlayIsImp0aSI6IjE3M2FmN2MwLThhNTAtMTFlYy1hZjY5LWFmMTJjODM3MjRkMiIsIm5iZiI6MTY0NTA4ODUyOCwic3ViIjoiMTczYWY3YzAtOGE1MC0xMWVjLWFmNjktYWYxMmM4MzcyNGQyIiwidmlkZW8iOnsicm9vbSI6InJvb20xIiwicm9vbUpvaW4iOnRydWV9fQ.SzndFlvveY1YbCHn1cvEK3KNK4hJtMklBJhaVYyzCX8...
17:03:40: [SignalEvent] Instance of 'SignalConnectedEvent'
17:03:40: onConnected subscriberPrimary: true, serverVersion: 0.15.4, iceServers: [urls: stun:stun.l.google.com:19302
urls: stun:stun1.l.google.com:19302
]
17:03:40: [PCTransport] creating {sdpSemantics: unified-plan, iceServers: [{urls: [stun:stun.l.google.com:19302, stun:stun1.l.google.com:19302]}]}
17:03:40: [PCTransport] creating {sdpSemantics: unified-plan, iceServers: [{urls: [stun:stun.l.google.com:19302, stun:stun1.l.google.com:19302]}]}
17:03:40: EventsListener<SignalEvent>#630597533 event was cancelled by func
17:03:40: Connected to LiveKit server, version: 0.15.4
17:03:40: Waiting to engine connect...
17:03:40: [SignalEvent] Instance of 'SignalOfferEvent'
17:03:40: [Engine#68236561] Received server offer(type: offer, null)
17:03:40: [SignalEvent] Instance of 'SignalTrickleEvent'
17:03:40: [SignalEvent] Instance of 'SignalTrickleEvent'
17:03:40: Created answer
17:03:40: got ICE candidate from peer
17:03:40: pc.getRemoteDescription Instance of 'RTCSessionDescription'
17:03:40: got ICE candidate from peer
17:03:40: pc.getRemoteDescription Instance of 'RTCSessionDescription'
17:03:40: [EngineEvent] Engine#68236561 EngineSubscriberIceStateUpdatedEvent(state: RTCIceConnectionState.RTCIceConnectionStateChecking, isPrimary: true)
17:03:40: subscriber onIceCandidate
17:03:40: subscriber onIceCandidate
17:03:40: [EngineEvent] Engine#68236561 EngineSubscriberIceStateUpdatedEvent(state: RTCIceConnectionState.RTCIceConnectionStateConnected, isPrimary: true)
17:03:40: [EngineEvent] Engine#68236561 Instance of 'EngineConnectedEvent'
17:03:40: EventsListener<EngineEvent>#861366913 event was cancelled by func
17:03:40: Room Connect completed
17:03:41: Server opened DC label: _reliable
17:03:41: Server opened DC label: _lossy
17:03:45: [SignalEvent] Instance of 'SignalConnectionQualityUpdateEvent'
17:03:45: [EngineEvent] Engine#68236561 Instance of 'SignalConnectionQualityUpdateEvent'
17:03:45: [ParticipantEvent] Instance of 'ParticipantConnectionQualityUpdatedEvent', will notifyListeners()
17:03:45: [RoomEvent] Instance of 'ParticipantConnectionQualityUpdatedEvent', will notifyListeners()
17:03:50: [SignalEvent] Instance of 'SignalParticipantUpdateEvent'
17:03:50: [EngineEvent] Engine#68236561 Instance of 'SignalParticipantUpdateEvent'
17:03:50: RemoteParticipant.updateFromInfo(info: sid: PA_TCeYwFpoFVCP
identity: 173af7c0-8a50-11ec-af69-af12c83724d0
state: ACTIVE
joinedAt: 1645088630
10: 6
)
17:03:50: [RoomEvent] Instance of 'ParticipantConnectedEvent', will notifyListeners()
17:03:50: [SignalEvent] Instance of 'SignalConnectionQualityUpdateEvent'
17:03:50: [EngineEvent] Engine#68236561 Instance of 'SignalConnectionQualityUpdateEvent'
17:03:51: [SignalEvent] Instance of 'SignalParticipantUpdateEvent'
17:03:51: [EngineEvent] Engine#68236561 Instance of 'SignalParticipantUpdateEvent'
17:03:51: RemoteParticipant.updateFromInfo(info: sid: PA_TCeYwFpoFVCP
identity: 173af7c0-8a50-11ec-af69-af12c83724d0
state: ACTIVE
tracks: {
  sid: TR_UCAaqMsEmWDW
  type: VIDEO
  name: output.h264
  mimeType: video/H264
12: [48]
}
joinedAt: 1645088630
10: 7
)
17:03:51: RemoteTrackPublication.updateFromInfo sid: TR_UCAaqMsEmWDW muted: false
17:03:51: RemoteTrackPublication.init track: null, info: sid: TR_UCAaqMsEmWDW
type: VIDEO
name: output.h264
mimeType: video/H264
12: [48]

17:03:51: RemoteTrackPublication.updateTrack track: null
17:03:51: [ParticipantEvent] Instance of 'TrackPublishedEvent', will notifyListeners()
17:03:51: [RoomEvent] Instance of 'TrackPublishedEvent', will notifyListeners()
17:03:51: [SignalEvent] Instance of 'SignalOfferEvent'
17:03:51: [Engine#68236561] Received server offer(type: offer, RTCSignalingState.RTCSignalingStateStable)
17:03:51: [WebRTC] pc.onTrack
17:03:51: [EngineEvent] Engine#68236561 Instance of 'EngineTrackAddedEvent'
17:03:51: EngineTrackAddedEvent trackSid:TR_UCAaqMsEmWDW
17:03:51: addSubscribedMediaTrack()
17:03:51: RemoteVideoTrack#270000457.start()
17:03:51: RemoteVideoTrack#270000457.enable() enabling MediaStreamTrackWeb#803177966...
17:03:51: RemoteTrackPublication.updateTrack track: Instance of 'RemoteVideoTrack'
17:03:51: [ParticipantEvent] Instance of 'TrackSubscribedEvent', will notifyListeners()
17:03:51: [RoomEvent] Instance of 'TrackSubscribedEvent', will notifyListeners()
17:03:51: Created answer
17:03:51: [SignalEvent] Instance of 'SignalStreamStateUpdatedEvent'
17:03:51: [EngineEvent] Engine#68236561 Instance of 'SignalStreamStateUpdatedEvent'
video track TR_UCAaqMsEmWDW subscribed true muted false
video track TR_UCAaqMsEmWDW subscribed true muted false
17:03:55: [SignalEvent] Instance of 'SignalConnectionQualityUpdateEvent'
17:03:55: [EngineEvent] Engine#68236561 Instance of 'SignalConnectionQualityUpdateEvent'
17:03:55: [ParticipantEvent] Instance of 'ParticipantConnectionQualityUpdatedEvent', will notifyListeners()
17:03:55: [RoomEvent] Instance of 'ParticipantConnectionQualityUpdatedEvent', will notifyListeners()
video track TR_UCAaqMsEmWDW subscribed true muted false
video track TR_UCAaqMsEmWDW subscribed true muted false

Application finished.

```

**Comment by hiroshihorie** [comment]
Can I see the result of your `flutter --version` ?
Looks like it's Chrome crashing, can you check if Chrome is latest ?

**Comment by ZestyXin** [comment]
> Can I see the result of your `flutter --version` ? Looks like it's Chrome crashing, can you check if Chrome is latest ?

hi @hiroshihorie, chrome version is `97.0.4692.71`.  i update it to `98.0.4758.102` now. but problem still exist.

flutter version
```
$ flutter --version
Flutter 2.10.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision db747aa133 (8 days ago) • 2022-02-09 13:57:35 -0600
Engine • revision ab46186b24
Tools • Dart 2.16.1 • DevTools 2.9.2
```

**Comment by davidzhao** [comment]
@ZestyXin the issue is your file is not encoded according to WebRTC standards. It's likely using b-frames which Chrome doesn't support.

Please use [these encoding instructions](https://github.com/livekit/server-sdk-go/tree/main#publishing-tracks-to-room) in order to create the file.
